autopkg/zentral-recipes

Nova/Nova.download.recipe
Nova/Nova.install.recipe
Nova/Nova.munki.recipe

These updates will download Nova dynamically instead of linking to a static URL. Importing and installing actions also utilize dmg (which is simpler to unpack/inspect) rather than pkg when possible.
Verbose run log below:
```
Processing Nova.download.recipe...
WARNING: Nova.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'Nova.zip',
'url': 'https://download.panic.com/nova/nova-latest.zip'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Tue, 15 Sep 2020 17:22:32 GMT
URLDownloader: Storing new ETag header: "5f60f858-2311106" …
```

Updates to Nova recipes

---

YubiKey_Manager/YubiKey_Manager.munki.recipe

MunkiImporter processor won't import Yubikey Manager 1.1.5 because CFBundleShortVersionString is "1.1" for both Yubikey Manager 1.1.0 and 1.1.5. 
Changing this value caused Yubikey Manager 1.1.5 to successfully import.

CFBundleVersion instead of CFBundleShortVersionString

---

YubiKey_Manager/YubiKey_Manager.munki.recipe

In https://github.com/autopkg/zentral-recipes/pull/11 I changed this to CFBundleVersion but Yubico has now released a package with this fixed: https://developers.yubico.com/yubikey-manager-qt/Releases/yubikey-manager-qt-1.1.5b-mac.pkg 
Distribution file: https://gist.github.com/discentem/b26c0dfdb20cc5bf0b078f7107183a65
```
brandon_kurtz@brandonurtzsMBP zentral-recipes % pkgutil --pkg-info com.yubico.ykman
package-id: com.yubico.ykman
version: 1.1.5
volume: /
location: Applications
install-time: 1605809596
```
We might even be able to revert https://github.com/autopkg/zentral-recipes/pull/10 but I don't necessarily want to throw away Ben's work given that it's not explicitly necessary. 
@macmule Thoughts on this?

Reverts version_comparison_key back to CFBundleShortVersionString

---

YubiKey_Manager/YubiKey_Manager.download.recipe

- Handles download links which may have letters in them e.g. 1.1.5b (thanks to @bp88 for help with the regex)
- see [https://developers.yubico.com/yubikey-manager-qt/Releases/](https://developers.yubico.com/yubikey-manager-qt/Releases/)
- Changes `plist_version_key` in Versioner Processor to `CFBundleShortVersionString` because this is the most accurate/specific version info in latest release

more yubikey manager changes

---

ngrok/ngrok.pkg.recipe

`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).

Adjust PkgCreator arguments

---

YubiKey_Manager/YubiKey_Manager.munki.recipe

`additional_pkginfo` belongs in the [MunkiPkginfoMerger](https://github.com/autopkg/autopkg/wiki/Processor-MunkiPkginfoMerger) processor.

Adjust MunkiPkginfoMerger arguments

---

FileMonitor/FileMonitor.download.recipe
FileMonitor/FileMonitorDMG.munki.recipe
ProcessMonitor/ProcessMonitor.download.recipe

Same changes as made in https://github.com/autopkg/zentral-recipes/pull/16.
However, I failed to include an additional regex change that _actually_ collects the version from the filename.  I didn't notice in my own test about that the version was only being included as part of the munkiimport on my test box and not actually naming the DMG correctly.
So I'm including the regex change for this and the previous PR.
Output for download with new regex:
```
autopkg run -vv ./FileMonitor.download.recipe                                                                         11s 18:38:15
Processing ./FileMonitor.download.recipe...
WARNING: ./FileMonitor.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': …
```

Add FileMonitorDMG.munki recipe & download regex fixes

---

Chrome_Remote_Desktop/ChromeRemoteDesktop.munki.recipe

Looks like this changed at some point in the past from a bundle to a .app, so this recipe should be able to pull the version again.

Pointing Versioner to ChromeRemoteDesktopHost.app, not .bundle

---

JamfProSwitcher/JamfProSwitcher.download.recipe

Jamf Pro Switcher release is changed from JamfProSwitcher-version to Jamf.Pro.Switcher-version.dmg

Change DL_REGEX to match new dmg naming

---

Secretive/Secretive.download.recipe
Secretive/Secretive.munki.recipe

This fixes spacing, ensures we get whatever .zip asset exists in GitHub (should the name change to include the version, for example), and adds a munki recipe.
Output from successful munki recipe run:
```
autopkg run -vv ~/Documents/git/zentral-recipes/Secretive/Secretive.munki.recipe
Processing /Users/autopkgadmin/Documents/git/zentral-recipes/Secretive/Secretive.munki.recipe...
WARNING: /Users/autopkgadmin/Documents/git/zentral-recipes/Secretive/Secretive.munki.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': '^.*\\.zip$',
'github_repo': 'maxgoedjen/secretive',
'include_prereleases': ''}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl …
```

Update Secretive.download and add Secretive.munki recipe

---

zentral_enrollpkgs/ZentralEnroll.download.recipe
zentral_enrollpkgs/ZentralEnroll.munki.recipe
zentral_enrollpkgs/ZentralEnrollPkgMetadataProvider.py

needed to leverage MunkiPkgInfoMerger otherwise I couldn't refer to the version variable ¯\_(ツ)_/¯

initial zentral enroll pkg recipes

---

zentral_enrollpkgs/ZentralEnroll.munki.recipe
zentral_enrollpkgs/ZentralEnrollPkgMetadataProvider.py

kindof silly, but added lower_cased variable and used it in the processor, tested to confirm it passed through to the munki installcheck

use prefix in name, fix script

---

swiftDialog/swiftDialog.download.recipe

Adding fix for swiftDialog regex

---

mist/mist.download.recipe

The asset_regex was looking only for a `major.minor` version number, not taking into account the possibility of a `major.minor.patch` number, as is the case for 1.7.0. Thankfully the GitHubReleasesInfoProvider seems to find the right file without the regex, so it's not necessary.

Remove asset_regex for mist.download as it was blocking 1.7.0

---

zentral_enrollpkgs/ZentralEnrollPkgMetadataProvider.py

As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …

Update Python path in processors to reflect changes in macOS 12.3+

---

swiftDialog/swiftDialog.download.recipe

- Simplify regex to find the first .pkg in the release. Prereleases were not properly being found.
- Download the actual package name from release instead of constructing. They're properly versioned as is.
- Fix mixed spaces and tabs.

swiftDialog prerelease fixes

---

mist/mist.download.recipe

Fixes #39 by adding the asset_regex argument to the GitHubReleasesInfoProvider processor to download pkg rather than dmg file.

Added asset_regex to download pkg rather than dmg

---

osquery-extension/macadmins-extension.install.recipe
osquery-extension/macadmins-extension.munki.recipe
osquery-extension/macadmins-extension.pkg.recipe
osquery-extension/readme.md

Note:
The new version of the pkg recipe will copy the Darwin binary and deploy to an updated OSQuery extension path located in 
`/opt/osquery-extensions/macadmins_extension.ext`

update osquery macadmins-extentions

---

Cutter/Cutter.download.recipe
Cutter/Cutter.install.recipe
Cutter/Cutter.pkg.recipe

This PR reworks the Cutter recipes to support the new version 2.x of Cutter, which is now powered by Rizin instead of radare2r. An ARCH input variable has been added which allows AutoPkg users to specify whether to download the Intel or Apple Silicon installer.
Verbose download/pkg recipe run output with default (Intel) architecture:
```
% autopkg run -vv Cutter.{download,pkg}.recipe
Processing Cutter.download.recipe...
WARNING: Cutter.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'Cutter\\-v[\\d\\.]+\\-macOS-x86_64\\.dmg',
'github_repo': 'rizinorg/cutter',
'include_prereleases': ''}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl …
```

Rework Cutter recipes for v2.x powered by Rizin

---

Brim/Brim.pkg.recipe
Crescendo/Crescendo.pkg.recipe
LanguageTool/LanguageToolDesktop.pkg.recipe
Nova/Nova.pkg.recipe
Proxyman/Proxyman.pkg.recipe
Secretive/Secretive.pkg.recipe
act/act.pkg.recipe
cue/cue.pkg.recipe
dog/dog.pkg.recipe
eapolcfg/eapolcfg.pkg.recipe
exa/exa.pkg.recipe
miniserve/miniserve.pkg.recipe
osquery-extension/macadmins-extension.pkg.recipe
tailwindcss/tailwindcss-cli.pkg.recipe
vector/vector.pkg.recipe
yq/yq.pkg.recipe

Hundreds of recipes dating from the very beginning of AutoPkg use the `options` key in the `pkg_request` argument of PkgCreator:
```xml
<key>options</key>
<string>purge_ds_store</string>
```
However, this key doesn't serve any purpose at all. The `options` key is ignored and not passed along to `pkgbuild`, regardless of its presence or contents. It appears that this has been the case since the very first public release of AutoPkg 0.1.0!
So this pull request (one of over 100) formally ends this practice and removes the unused and unneeded `options` key from all recipes in the AutoPkg org that use PkgCreator.
Thanks for considering!
_This PR was submitted using [Repo Lasso](https://github.com/homebysix/repo-lasso) v1.2.0._

Removal of unused `options` from PkgCreator arguments
